#+TITLE: Emacs Config

* General Settings

Typing =:ensure t= everywhere is very bothersome so I'd rather *not* do that.

#+BEGIN_SRC emacs-lisp
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+END_SRC

I don't want my Emacs to create loads of backup files, swap files, etc.

#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+END_SRC

Nor do I need all the (Windows 2000-esque) UI.

#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (menu-bar-mode -1)
#+END_SRC

When I fire up Emacs I want to be greeted with the =*scratch*= buffer, not the weird GNU screen.

#+BEGIN_SRC emacs-lisp
  (setq inhibit-splash-screen t)
#+END_SRC

The whole yes or no prompt takes too much time to type out. y and n is much better.

#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

UTF-8 is good and should be the default for everything.

#+BEGIN_SRC emacs-lisp
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
#+END_SRC

Which key makes Emacs self documenting.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :config
    (which-key-mode))
#+END_SRC

Tramp is awesome for editing remote files.
By default it's slow as fuck though.

#+BEGIN_SRC emacs-lisp
  (setq tramp-default-method "ssh")
#+END_SRC

=direnv= allows me to have my nix stuff in Emacs.

#+BEGIN_SRC emacs-lisp
  (use-package direnv
    :config
    (direnv-mode))
#+END_SRC

* Looks

** =nyan-mode=

Nya-nya-nya-nya-nya...

#+BEGIN_SRC emacs-lisp
  (use-package nyan-mode
    :config
    (nyan-mode))
#+END_SRC

** Font

I prefer cherry font.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist
               '(font . "cherry-13"))
#+END_SRC

** Line numbers

#+BEGIN_SRC emacs-lisp
  (global-linum-mode 1)
#+END_SRC

Linum mode makes =doc-view-mode= almost unusable, so we better disable it there.

#+BEGIN_SRC emacs-lisp
  (add-hook 'doc-view-mode-hook (lambda ()
                                  (linum-mode -1)))
#+END_SRC

** Color Theme

I'm using a base16 theme at the moment, because I'm lazy. Might change in the future.

#+BEGIN_SRC emacs-lisp
  (use-package base16-theme
    :config
    (load-theme 'base16-mocha t))
#+END_SRC

** Beacon

Highlights the cursor each time I switch windows.

#+BEGIN_SRC emacs-lisp
  (use-package beacon
    :config
    (beacon-mode 1))
#+END_SRC

* Editing

** =evil-mode=

Emacs lacks a good editor.

#+BEGIN_SRC emacs-lisp
  (use-package evil
    :config
    (evil-mode 1))
#+END_SRC

*** =evil-surround=

Allows me to surround stuff in parens etc.

#+BEGIN_SRC emacs-lisp
  (use-package evil-surround
    :config
    (global-evil-surround-mode 1))
#+END_SRC

*** =org-evil=

Makes Org-mode intuitive with evil.

#+BEGIN_SRC emacs-lisp
  (use-package org-evil)
#+END_SRC

*** =evil-collection=

Sane defaults for most modes.

#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :config
    (evil-collection-init))
#+END_SRC

** general.el

#+BEGIN_SRC emacs-lisp
  (use-package general
    :init
    (setq general-override-states '(insert
                                    emacs
                                    hybrid
                                    normal
                                    visual
                                    motion
                                    operator
                                    replace))
    :config
    (general-create-definer bft-leader-def
      :prefix "SPC")
    (general-create-definer bft-local-leader-def
      :prefix "SPC m")

    (bft-leader-def
      :keymaps 'normal
      "a" 'org-agenda
      "l" 'org-store-link
      "c" 'org-capture
      "w" 'save-buffer
      "f" 'counsel-find-file
      "m" 'delete-other-windows
      "d" 'delete-window
      "o" 'split-window-right
      "u" 'split-window-below
      "h" 'evil-window-left
      "j" 'evil-window-down
      "k" 'evil-window-up
      "l" 'evil-window-right
      "b" 'counsel-switch-buffer)

    (general-evil-setup)
    (general-imap "k"
      (general-key-dispatch 'self-insert-command
        :timeout 0.25
        "j" 'evil-normal-state)))
#+END_SRC

** =eval-and-replace=

Cool thing for on the spot meta programming.

#+BEGIN_SRC emacs-lisp
  (defun eval-and-replace ()
    "Replace the preceding sexp with its value."
    (interactive)
    (backward-kill-sexp)
    (condition-case nil
	(prin1 (eval (read (current-kill 0)))
	       (current-buffer))
      (error (message "Invalid expression")
	     (insert (current-kill 0)))))

  (global-set-key (kbd "C-c e") 'eval-and-replace)
#+END_SRC

** Trailing Whitespace

I *hate* trailing whitespace with a passion, so I want to see it.

#+BEGIN_SRC emacs-lisp
  (setq-default show-trailing-whitespace t)
#+END_SRC

I also want it to be removed automatically, but only on lines I edited.

#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :config
    (ws-butler-global-mode))
#+END_SRC

** =expand-region=

#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :commands
    er/expand-region
    :bind
    ("C-=" . er/expand-region))
#+END_SRC

** Show parens pairs

Lots of languages use a lot of parens (lisp...). Would be neat if they'd show up.

#+BEGIN_SRC emacs-lisp
  (setq show-paren-delay 0)
  (show-paren-mode 1)
#+END_SRC

** Insert parens pairs

#+BEGIN_SRC emacs-lisp
  (electric-pair-mode 1)
#+END_SRC

** Move between windows

#+BEGIN_SRC emacs-lisp
  (require 'windmove)
  (windmove-default-keybindings)
  (setq windmove-wrap-around t)
#+END_SRC

** Ivy

Ivy for completing stuff, etc. is huge.

#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :config
    (ivy-mode)
    :bind
    ("C-s" . swiper)
    ("M-x". counsel-M-x))
#+END_SRC

** =flycheck=

Syntax checking is good.

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :config
    (global-flycheck-mode))
#+END_SRC

** =company-mode=

Completes anything.

#+BEGIN_SRC emacs-lisp
  (use-package company
    :config
    (global-company-mode 1))
#+END_SRC

** Avy

Allows to move between stuff in a quick fashion.

#+BEGIN_SRC emacs-lisp
  (use-package avy
    :bind
    ("M-s" . avy-goto-char)
    ("M-G" . avy-goto-line))
#+END_SRC

** =popup-kill-ring=

Allows me to see the whole kill-ring with a single =M-y=.

#+BEGIN_SRC emacs-lisp
  (use-package popup-kill-ring
    :bind
    ("M-y" . popup-kill-ring))
#+END_SRC

** Sudo Edit

Super helpful when you forget to open a file as root.

#+BEGIN_SRC emacs-lisp
  (use-package sudo-edit
    :config
    (bft-leader-def
      :keymaps 'normal
      "s s" 'sudo-edit))
#+END_SRC

** Easy window manipulation

Shorter hotkeys.
Windows get manipulated all the time.
These are in place even though general.el is used, because some buffers don't just work like that.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-1") 'delete-other-windows)
  (global-set-key (kbd "C-0") 'delete-window)
  (global-set-key (kbd "C-2") 'split-window-below)
  (global-set-key (kbd "C-3") 'split-window-right)
#+END_SRC

* Project

** Magit

The only good interface for =git=.

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :commands
    magit-statue
    :bind
    ("M-g" . magit-status))
#+END_SRC

** Projectile

Neat project managing thing.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :config
    (projectile-mode 1)
    (bft-leader-def
      :keymaps 'normal
      "p" 'projectile-command-map))
#+END_SRC

* Languages

** Org-mode

Super tiresome to type all these =emacs-lisp= source blocks.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
	       '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC

Syntax highlighting in HTML exports are nice.

#+BEGIN_SRC emacs-lisp
  (use-package htmlize)
#+END_SRC

All the stars are super noisy. Org-mode has a =indent-mode= for this.

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook
	    (lambda ()
	      (org-indent-mode 1)))
#+END_SRC

Twitter bootstrap export is amazing and good.

#+BEGIN_SRC emacs-lisp
  (use-package ox-twbs)
#+END_SRC

*** Agenda

**** Style

Custom agenda that shows priority stuff and catogerizes everything.[fn:https://blog.aaronbieber.com/2016/09/24/an-agenda-for-life-with-org-mode.html]

Emacs doesn't offer skipping habits or priority =A= stuff, so let's write functions for that.

#+BEGIN_SRC emacs-lisp
  (defun bft-org-skip-subtree-if-priority (priority)
    "Skip an agenda subtree if it has a priority of PRIORITY.

  PRIORITY may be one of the characters ?A, ?B, or ?C."
    (let ((subtree-end (save-excursion (org-end-of-subtree t)))
          (pri-value (* 1000 (- org-lowest-priority priority)))
          (pri-current (org-get-priority (thing-at-point 'line t))))
      (if (= pri-value pri-current)
          subtree-end
        nil)))

  (defun bft-org-skip-subtree-if-habit ()
    "Skip an agenda entry if it has a STYLE property equal to \"habit\"."
    (let ((subtree-end (save-excursion (org-end-of-subtree t))))
      (if (string= (org-entry-get nil "STYLE") "habit")
          subtree-end
        nil)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-custom-commands
        '(("d" "Daily agenda and all TODOs"
           ((tags "PRIORITY=\"A\""
                  ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                   (org-agenda-overriding-header "High-priority unfinished tasks:")))
            (agenda "" ((org-agenda-ndays 1)))
            (alltodo ""
                     ((org-agenda-skip-function '(or (bft-org-skip-subtree-if-habit)
                                                     (bft-org-skip-subtree-if-priority ?A)
                                                     (org-agenda-skip-if nil '(scheduled deadline))))
                      (org-agenda-overriding-header "ALL normal priority tasks:"))))
           ((org-agenda-compact-blocks t)))))
#+END_SRC

**** Files

Add all my org files.

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files '("~/org/"))
#+END_SRC

** =AucTeX=

Since =AucTeX= overrides =tex= for some reason this is a weird hack that supposedly works.

#+BEGIN_SRC emacs-lisp
  (use-package tex
    :ensure auctex)
#+END_SRC

** =nix-mode=

#+BEGIN_SRC emacs-lisp
  (use-package nix-mode)
#+END_SRC

** =CC-mode=

I don't want Emacs to insert Tabs everywhere.

#+BEGIN_SRC emacs-lisp
  (setq indent-tabs-mode nil)
#+END_SRC

The way indentation is handled by default is horrible.
Let's fix that.

#+BEGIN_SRC emacs-lisp
  (setq c-default-style "user"
        c-basic-offset 4)
#+END_SRC

** Emacs Lisp

Emacs has a built in mode for elisp documentation.

#+BEGIN_SRC emacs-lisp
  (eldoc-mode 1)
#+END_SRC

** Web

*** =impatient-mode=

=impatient-mode= helps quick development

#+BEGIN_SRC emacs-lisp
  (use-package impatient-mode)
#+END_SRC

*** =emmet-mode=

This makes it easy to write bad HTML fast.

# TODO: Look into =zencoding-mode=

#+BEGIN_SRC emacs-lisp
  (use-package emmet-mode
    :config
    (emmet-mode))
#+END_SRC

** Meson

#+BEGIN_SRC emacs-lisp
  (use-package meson-mode)
#+END_SRC

** C

*** Irony-mode

#+BEGIN_SRC emacs-lisp
  (use-package irony
    :config
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))
#+END_SRC

Irony for autocompletion

#+BEGIN_SRC emacs-lisp
  (use-package company-irony
    :config
    (add-to-list 'company-backends 'company-irony))
#+END_SRC

Irony as a flycheck backend

#+BEGIN_SRC emacs-lisp
  (use-package flycheck-irony
    :config
    (add-hook 'flycheck-mode-hook 'flycheck-irony-setup))
#+END_SRC
