#! /bin/sh

sxhkd &

xbanish &

polybar nice &

xsetroot -solid "#1d1f21"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            0 #12

bspc config top_padding           -7

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color "#7d3750"
bspc config normal_border_color "#1d1f21"
bspc config presel_feedback_color "#7d3750"

bspc rule -a Gimp desktop='^8' state=floating follow=on

