#!/usr/bin/env bash

#   ___________
#  < autostart >
#   -----------
#          \   ^__^
#           \  (oo)\_______
#              (__)\       )\/\
#                  ||----w |
#                  ||     ||

hc() {
    herbstclient "$@"
}

# remove all existing keybindings
hc keyunbind --all
hc mouseunbind --all

Mod=Mod4

modbind() {
	key=$1
	shift
	hc keybind $Mod-$key $@
}

hc emit_hook reload

xsetroot -solid "#6d828e"

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

modbind Shift-q quit
modbind Shift-r reload
modbind w       close
modbind Shift-w spawn ~/dotfiles/misc/scripts/hl-swap.sh close

modbind Return  spawn urxvtc
modbind q       spawn qutebrowser
modbind space   spawn rofi -show drun
modbind Shift-x spawn slock
modbind b       spawn emacs

modbind y       spawn ~/dotfiles/misc/scripts/dunst-time.sh
modbind Shift-y spawn ~/dotfiles/misc/scripts/dunst-battery.sh

modbind e             spawn ~/dotfiles/misc/scripts/screehot full
modbind Shift-e       spawn ~/dotfiles/misc/scripts/screehot sel
modbind Control-e     spawn ~/dotfiles/misc/scripts/screehot win
modbind Alt-e         spawn ~/dotfiles/misc/scripts/screehot full upload
modbind Alt-Shift-e   spawn ~/dotfiles/misc/scripts/screehot sel upload
modbind Alt-Control-e spawn ~/dotfiles/misc/scripts/screehot win upload

# backlight
modbind z spawn xbacklight -dec 5
modbind x spawn xbacklight -inc 5

# movement
modbind Left  focus left
modbind Down  focus down
modbind Up    focus up
modbind Right focus right
modbind h     focus left
modbind j     focus down
modbind k     focus up
modbind l     focus right

modbind semicolon spawn ~/dotfiles/misc/scripts/hl-swap.sh auto

# moving clients
modbind Shift-Left  shift left
modbind Shift-Down  shift down
modbind Shift-Up    shift up
modbind Shift-Right shift right
modbind Shift-h     shift left
modbind Shift-j     shift down
modbind Shift-k     shift up
modbind Shift-l     shift right

# splitting
modbind u split bottom 0.5
modbind o split right  0.5

modbind Control-space split explode

# resize
resizestep=0.05
modbind Control-h     resize left  +$resizestep
modbind Control-j     resize down  +$resizestep
modbind Control-k     resize up    +$resizestep
modbind Control-l     resize right +$resizestep
modbind Control-Left  resize left  +$resizestep
modbind Control-Down  resize down  +$resizestep
modbind Control-Up    resize up    +$resizestep
modbind Control-Right resize right +$resizestep

# layouting
modbind r remove
modbind s floating   toggle
modbind f fullscreen toggle
modbind p pseudotile toggle

# focus
modbind BackSpace cycle_monitor
modbind Tab       cycle_all +1
modbind Shift-Tab cycle_all -1
modbind c         cycle
modbind i         jumpto urgent

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
modbind Shift-space                                                     \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#dee2e2'
hc set frame_border_normal_color '#373737'
hc set frame_bg_normal_color '#e3efef'
hc set frame_bg_active_color '#e3efef'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 0
hc set frame_transparent_width 0
hc set frame_gap 20

hc attr theme.active.color '#6d828e'
hc attr theme.normal.color '#e3efef'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color '#1f1f23'
hc attr theme.border_width 6
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#222222'
hc attr theme.active.inner_color '#7d3750'
hc attr theme.active.outer_color '#7d3750'
hc attr theme.background_color '#1f1f23'

hc set window_gap 9
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc pad 0 32 32 32 32

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

xbanish &
