#!/bin/sh

herbstclient --idle | while read -r event
do
	case "$event" in
		*'tag_changed'*)
             # Empty tag
			if [ "$(herbstclient dump)" = "(clients vertical:0)" ]
			then
				herbstclient set frame_bg_transparent 1
			else
				herbstclient set frame_bg_transparent 0
			fi
			;;
	esac
done
