#!/usr/bin/env bash
#
# cowfetch - system info specific for me

get_wm() {
	local wm
    if [[ "$DISPLAY" && "$os" != "Mac OS X" && "$os" != "FreeMiNT" ]]; then
        id="$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)"
        id="${id##* }"
        wm="$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)"
        wm="${wm/*WM_NAME = }"
        wm="${wm/\"}"
        wm="${wm/\"*}"

        # Window Maker does not set _NET_WM_NAME
        [[ "$wm" =~ "WINDOWMAKER" ]] && wm="wmaker"

        # Fallback for non-EWMH WMs.
        [[ -z "$wm" ]] && \
            "$(ps -e | grep -m 1 -o -F \
                               -e "catwm" \
                               -e "dwm" \
                               -e "2bwm" \
                               -e "monsterwm" \
                               -e "tinywm")"
	fi

	echo "$wm"
}

hostname=$(hostname)
uptime=$(uptime | cut -d' ' -f 4-6 | sed 's/.$/ hours/')
wm=$(get_wm)
term=${TERMINAL:st}
shell="${SHELL##*/}"

cat <<EOF
${USER}@${hostname}
--
up: ${uptime}
wm: ${wm}
tm: ${term}
sh: ${shell}
EOF

if uname -r | grep 'arch' > /dev/null; then
	echo -e '\nI use arch btw'
fi
