#!/bin/sh
#
# dnif - find, but backwards and different

[[ -z "$1" ]] && exit 1

while ! [[ -e "$1" ]]; do
    if [[ "${PWD}" = "/" ]]; then
        echo \'"$1"\' not found
        exit 1
    fi

    cd ..
done

shift
eval "$@"
