#!/usr/bin/env bash

case "$1" in
	full)
		scrot='maim -u'
		;;
	sel)
		scrot='maim -su'
		;;
	win)
		scrot='maim -slu'
		;;
	help|*)
		echo "$(basename $0) full|sel|win"
		exit
		;;
esac

case "$2" in
	upload)
		$scrot 2> /dev/null | curl -F c=@- "https://ptpb.pw/?u=1" 2> /dev/null | head -c -1 | xclip -selection clipboard
		;;
	copy|*)
		$scrot 2> /dev/null | xclip -selection clipboard -t image/png
		;;
esac
