#!/usr/bin/env bash

case "$1" in
	full)
		scrot='maim -u'
		;;
	sel)
		scrot='maim -su'
		;;
	win)
		scrot='maim -slu'
		;;
	help|*)
		echo "$(basename $0) full|sel|win"
		exit
		;;
esac

case "$2" in
	upload)
		output="curl -F c=@- "https://ptpb.pw/?u=1" | head -c -1 | xclip -selection clipboard"
		;;
	copy|*)
		output="xclip -selection clipboard -t image/png"
		;;
esac

eval "$scrot | $output"
