## Options
# use tabs instead of spaces
set-option global indentwidth 4
set-option global tabstop     4

# don't change title all the time
set-option global ui_options  ncurses_set_title=false

## Maps
# faster save (for compulsive saving)
map global user w :w<ret>
# switch buffers
map global user n :buffer-previous<ret>
map global user m :buffer-next<ret>
map global user b :buffer<space>

## Hooks
# highlighters
hook global WinCreate .* %{
	# relative line numbers
	add-highlighter window number_lines -relative -hlcursor

	# matching brackets
	add-highlighter window show_matching

	# trailing spaces
	add-highlighter window regex '\h+$' 0:black,red

	# softwraping
	add-highlighter window wrap
}

hook global InsertChar j %{ try %{
  exec -draft hH <a-k>kj<ret> d
  exec <esc>
}}
